// I use gemini to help me lmao

// Ensure OmegaNum is loaded safely in both browser and Node environments
const OmegaNum = window.OmegaNum || require("omega-num");

const PHI = new OmegaNum((1 + Math.sqrt(5)) / 2);

document.getElementById('calcInput').addEventListener('keydown', function(e) {
  if (e.key === 'Enter') {
    const input = this.value.trim();
    if (input) {
      processGoogology(input);
    }
  }
});

/**
 * CLEAN LATEX FORMATTER FOR OMEGANUM
 * Converts hyper-dimensional OmegaNum objects into clean mathematical notation.
 */
function renderOmegaNumResult(display, omniValue) {
  let latex = "";

  if (omniValue.lt(1e10)) {
    latex = Math.floor(omniValue.toNumber()).toString();
  } else {
    // OmegaNum's native string output handles huge arrows natively (e.g., "10^^^5")
    // We convert its standard string output into clean LaTeX formatting
    let rawStr = omniValue.toString();
    
    if (rawStr.includes('e')) {
      // Handle standard scientific notation or standard power towers
      latex = rawStr.replace(/e\+/g, 'e')
                    .replace(/e/g, '\\times 10^{') + '}'.repeat((rawStr.match(/e/g) || []).length);
    } else if (rawStr.includes('^')) {
      // Handle hyper-operations / Knuth arrow notations generated by OmegaNum
      // e.g., "10^^5" becomes "10 \\uparrow\\uparrow 5"
      latex = rawStr.replace(/\^\^/g, ' \\uparrow\\uparrow ')
                    .replace(/\^/g, ' \\uparrow ');
    } else {
      latex = rawStr;
    }
  }

  renderMath(display, `\\text{Result: } ${latex}`);
}

/**
 * OMEGANUM FACTORIAL ENGINE
 * Uses Stirling's approximation scales to massive OmegaNum sizes.
 */
function omegaFactorial(n) {
  if (n.lt(0)) return new OmegaNum(NaN);
  if (n.isZero()) return new OmegaNum(1);
  if (n.lte(20)) {
    let result = new OmegaNum(1);
    for (let i = 2; i <= n.toNumber(); i++) {
      result = result.times(i);
    }
    return result;
  }

  // Stirling's Approximation using OmegaNum functions
  // ln(n!) ≈ 0.5 * ln(2 * pi * n) + n * ln(n) - n
  const pi = OmegaNum.pi;
  
  const part1 = n.times(pi).times(2).ln().times(0.5);
  const part2 = n.times(n.ln());
  const lnFact = part1.plus(part2).minus(n);

  return lnFact.exp();
}

/**
 * SAFE MATHEMATICAL EXPRESSION EVALUATOR
 * Parsed right-to-left to respect the mathematical order of operations for power towers.
 */
function evaluateOmegaExpression(expr) {
  // Handle Power Towers (Right-Associative: 2^3^2 = 2^(3^2))
  if (expr.includes('^')) {
    const parts = expr.split('^');
    let current = evaluateOmegaExpression(parts[parts.length - 1]);
    
    for (let i = parts.length - 2; i >= 0; i--) {
      let base = evaluateOmegaExpression(parts[i]);
      current = base.pow(current);
    }
    return current;
  }

  // Handle Multiplication
  if (expr.includes('*')) {
    return expr.split('*')
               .map(evaluateOmegaExpression)
               .reduce((a, b) => a.times(b));
  }

  // Handle Division
  if (expr.includes('/')) {
    return expr.split('/')
               .map(evaluateOmegaExpression)
               .reduce((a, b) => a.div(b));
  }

  // Handle Addition
  if (expr.includes('+')) {
    return expr.split('+')
               .map(evaluateOmegaExpression)
               .reduce((a, b) => a.plus(b));
  }

  // Constants Mapping
  if (expr === 'phi') return PHI;
  
  // Strip stray outer parentheses
  let cleanExpr = expr.replace(/[()]/g, '');
  return new OmegaNum(cleanExpr);
}

/**
 * MAIN GOOGOLOGY PROCESSOR
 */
function processGoogology(rawInput) {
  const display = document.getElementById('outputDisplay');
  
  let expr = rawInput.toLowerCase().replace(/x/g, '*').replace(/\s+/g, '');
  
  // Custom definitions for structural Googology terms
  if (expr === 'googol') { 
    return renderOmegaNumResult(display, new OmegaNum("1e100")); 
  }
  if (expr === 'googolplex') { 
    return renderOmegaNumResult(display, OmegaNum.pow(10, new OmegaNum("1e100"))); 
  }
  if (expr === 'googolduplex') {
    return renderOmegaNumResult(display, OmegaNum.pow(10, OmegaNum.pow(10, new OmegaNum("1e100"))));
  }

  // 1. FACTORIAL ENGINE
  if (expr.endsWith('!')) {
    let numStr = expr.slice(0, -1);
    try {
      let innerValue = evaluateOmegaExpression(numStr);
      if (!innerValue.isNaN()) {
        let result = omegaFactorial(innerValue);
        renderOmegaNumResult(display, result);
        return;
      }
    } catch(err) {
      renderMath(display, `\\text{Error: Invalid factorial input.}`);
      return;
    }
  }

  // 2. STANDARD & TOWER ARRAYS ENGINE
  try {
    let result = evaluateOmegaExpression(expr);
    if (!result.isNaN() && result.isFinite()) {
      renderOmegaNumResult(display, result);
      return;
    }
  } catch (e) {
    // Fall through to error
  }

  renderMath(display, `\\text{Error: Could not compute.}`);
}

// MathJax Renderer
function renderMath(element, latex) {
  element.innerHTML = `\\[ ${latex} \\]`;
  MathJax.typesetPromise([element]).catch((err) => console.log(err));
}
